# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build container and deploy image

env:
  registryName: 'v6ppu6urmilhmmpnpreg.azurecr.io'
  repositoryName: 'techboost/dotnetcoreapp'
  dockerFolderPath: 'Application/src/RazorPagesTestSample'
  tag: ${{ github.run_number }}
  prefix: 'v6ppu6urmilhm'

on:
  push:
    branches: [ 'main' ]
    paths:
      - 'Application/**'
  pull_request:
    branches: [ 'main' ]
    paths:
      - 'Application/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Build
      run: dotnet build --no-restore ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj

  dockerBuildPush:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USER }}
        password: ${{ secrets.ACR_PASSWORD }}
        logout: true
    - name: Docker Build
      run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath
    - name: Docker Push
      run: docker push $registryName/$repositoryName:$tag

  deploy-dev:
    runs-on: ubuntu-latest
    needs: dockerBuildPush
    environment:
      name: dev
      url: https://$prefix-dev.azurewebsites.net/
    steps:
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy container image to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: $prefix-dev
          images: $registryName.azurecr.io/techboost/dotnetcoreapp:${{ github.run_number }}

  deploy-test:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: test
      url: https://$prefix-test.azurewebsites.net/
    steps:
    - uses: actions/checkout@v3
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy container image to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: $prefix-test
        images: $registryName.azurecr.io/techboost/dotnetcoreapp:${{ github.run_number }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-test
    environment:
      name: prod
      url: https://$prefix-prod.azurewebsites.net/
    steps:
    - uses: actions/checkout@v3
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy container image to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: $prefix-prod
        images: $registryName.azurecr.io/techboost/dotnetcoreapp:${{ github.run_number }}
